server:
  port: 8080
spring:
  application:
    name: start
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useSSL=false&useUnicode=true&characterEncoding=utf-8&servetTimeZone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true


mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.springstart.demo.entity